version: "3.9"

services:
  mongo:
    image: mongo:4.0.0
    container_name: mongodb-test
    ports:
      - "27017:27017"

  test:
    build: .
    container_name: ecommerce-api-test
    command: "npm run test"
    volumes:
      - ./coverage:/app/coverage
    environment:
      NODE_ENV: 'test'
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: ecommerce-test
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 5
    depends_on:
      - mongo

volumes:
  coverage: