version: "3.9"

services:
  mongo:
    image: mongo:4.0.0
    container_name: mongodb-dev
    ports:
      - "27018:27017"
    volumes:
      - ./db/data:/data/db

  ecommerce-api:
    build: .
    container_name: ecommerce-api
    command: "npm run dev-start"
    restart: 'always'
    environment:
      NODE_ENV: 'dev'
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: ecommerce-dev
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 5
    ports:
      - "9000:9000"
    depends_on:
      - mongo

volumes:
  coverage: